# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Makes a dummy config for security purposes
      - name: Create dummy Amplify config
        run: |
          cd Frontend/SkillTrackFrontend
          mkdir -p src
          echo '{}' > src/amplifyconfiguration.json
      
      # Installs dependencies
      - name: Install dependencies & copy into API
        run: |
          cd Frontend/SkillTrackFrontend
          npm ci
          cp src/constants/example-api.ts src/constants/api.ts

      # Verifies Expo can compile. Test cases will go after this once written.
      - name: Verify Expo can compile
        run: |
          cd Frontend/SkillTrackFrontend
          npx expo export --platform web --output-dir dist --non-interactive
      # Checks JavaScript code quality
      - name: Lint
        run: |
          cd Frontend/SkillTrackFrontend
          npm i -D eslint
          npx eslint . || true
